name: Deploy React App to Debian VPS

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      reason:
        description: "Deployment reason"
        required: false
        default: "Manual deployment"
      timestamp:
        description: "Event timestamp"
        required: false

env:
  BUILD_DIR: "dist"
  NODE_VERSION: "24"
  TARGET_DIR: "/home/${{ secrets.REMOTE_USER }}/app"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      # - name: Cache Dependencies and Build
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       ~/.pnpm-store
      #       ${{ github.workspace }}/.next/cache
      #     # Generate a new cache whenever packages or source files change
      #     key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx', '**/*.json') }}
      #     # If source files changed but packages didn't, rebuild from a prior cache
      #     restore-keys: |
      #       ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-
      #       ${{ runner.os }}-nextjs-

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Build
        run: pnpm run build

      - name: Deploy to VPS
        uses: easingthemes/ssh-deploy@v5.1.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "${{ env.BUILD_DIR }}/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ env.TARGET_DIR }}
